language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
install:
  - pip install . nose coverage coveralls
script:
  - nosetests --with-coverage --cover-package=clld
after_success:
  - coveralls
