language: python
matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
cache: pip
before_cache: rm -f $HOME/.cache/pip/log/debug.log
before_install: pip install codecov
install: pip install tox
script: tox
after_success:
  - tox -e coverage-report
  - codecov
